version: '3.8'

services:
  credit-advice:
    build: .
    container_name: credit-advice
    restart: unless-stopped
    networks:
      - credit
    depends_on:
      - nginx-credit-advice

  nginx-credit-advice:
    image: nginx:alpine
    container_name: nginx-credit-advice
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    ports:
      - "6002:6002"
    networks:
      - credit

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: credit-advice-tunnel
    restart: unless-stopped
    command: tunnel run --url http://nginx-credit-advice:6002
    networks:
      - credit

networks:
  credit:
    driver: bridge
