export const Credentials = {
  username: "smct",
  password: "123456",
  name: "SMCT Credit Advice",
  token:
    "SMCT-TOKEN-N3RlcllXM0h2UmtFJTJGQlVXcE5EJTJCSm5FSjV0TjBvJTJGdmxGVnMlMkZrT2lUTlFhTnlWbkclMkJjRHRZJTJGYnQyT0lZZkJzRUUlMkI3SnElMkZ1MGJ2ZlFJVklFYVZXTkFBRGclMkJkZkJoNWxFZVYlMkZYU25ZeWclMkYxYjU5TWxCT25RWk1TJTJCa0ZpMVVTVUZvUkVsZVdxRlNHSXZNSDRjVExRZ1VRM2xqZEpQRmROcTVTT3h6JTJGUHJqZExEZ0JYZElRYzl0RlYxSkVqZ1QzWm5KUVZlYlZTSFV2VnYlMkZvcnZlJTJGdlRMT2J5dzBq",
};
